name: Scala CI

on:
  push:
    branches: [ trunk ]
    paths:
     - 'expensereport-scala/**'
  pull_request:
    branches: [ trunk ]
    paths:
     - 'expensereport-scala/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    - run: sbt compile scalafmtCheckAll
      working-directory: expensereport-scala

